# Generated by Django 5.0.4 on 2024-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(max_length=100),
        ),
    ]
