# Generated by Django 5.0.4 on 2024-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_event_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(default='', upload_to='event_picture/'),
        ),
    ]
